import "../styles/globals.css";
import Navbar from "@/components/Organisms/Navbar";
import Container from "@/components/Atoms/Container";
import { CharactersProvider } from "@/contexts/CharactersContext";

export const metadata = {
  title: "Marvel App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="es">
      <body>
        <main className="min-h-screen pb-8 bg-background bg-blend-multiply">
          <Navbar />
          <CharactersProvider>
            <Container className="mt-[2.375rem]">{children}</Container>
          </CharactersProvider>
        </main>
      </body>
    </html>
  );
}

